// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.web;

import com.example.model.ToDo;
import com.example.service.ToDoService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class ToDoController_getAllToDodb6a2452b4Test {

    @InjectMocks
    ToDoController toDoController;

    @Mock
    ToDoService toDoService;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetAllToDo() {
        ToDo todo1 = new ToDo();
        todo1.setId(1L);
        todo1.setText("ToDo1");

        ToDo todo2 = new ToDo();
        todo2.setId(2L);
        todo2.setText("ToDo2");

        when(toDoService.getAllToDo()).thenReturn(Arrays.asList(todo1, todo2));

        ResponseEntity<List<ToDo>> response = toDoController.getAllToDo();

        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertEquals(2, response.getBody().size());
        assertEquals("ToDo1", response.getBody().get(0).getText());
        assertEquals("ToDo2", response.getBody().get(1).getText());
    }

    @Test
    public void testGetAllToDoEmpty() {
        when(toDoService.getAllToDo()).thenReturn(Arrays.asList());

        ResponseEntity<List<ToDo>> response = toDoController.getAllToDo();

        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertEquals(0, response.getBody().size());
    }
}
