// Test generated by RoostGPT for test dmtest using AI Type Open AI and AI Model gpt-4-0314

package com.example.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ErrorResponse_setErrorCode_c642801da1_Test {

    private ErrorResponse errorResponse;

    @BeforeEach
    public void setUp() {
        errorResponse = new ErrorResponse();
    }

    @Test
    public void testSetErrorCode_success() {
        int expectedErrorCode = 404;
        errorResponse.setErrorCode(expectedErrorCode);
        assertEquals(expectedErrorCode, errorResponse.getErrorCode());
    }

    @Test
    public void testSetErrorCode_edgeCase() {
        int expectedErrorCode = Integer.MAX_VALUE;
        errorResponse.setErrorCode(expectedErrorCode);
        assertEquals(expectedErrorCode, errorResponse.getErrorCode());
    }
}
