// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ErrorResponse_getMessage6d271e6330Test {

    private ErrorResponse errorResponse;

    @BeforeEach
    public void setup() {
        errorResponse = new ErrorResponse();
    }

    @Test
    public void testGetMessage_Success() {
        String expectedMessage = "This is a test message";
        errorResponse.setMessage(expectedMessage);
        String actualMessage = errorResponse.getMessage();

        assertEquals(expectedMessage, actualMessage, "The expected message does not match the actual message");
    }

    @Test
    public void testGetMessage_Empty() {
        String expectedMessage = "";
        errorResponse.setMessage(expectedMessage);
        String actualMessage = errorResponse.getMessage();

        assertEquals(expectedMessage, actualMessage, "The expected message does not match the actual message");
    }
}
