// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ErrorResponse_setMessage4456678576Test {

    private ErrorResponse errorResponse;

    @BeforeEach
    public void setup() {
        errorResponse = new ErrorResponse();
    }

    @Test
    public void testSetMessage_Success() {
        String expectedMessage = "This is a test message";
        errorResponse.setMessage(expectedMessage);
        assertEquals(expectedMessage, errorResponse.getMessage());
    }

    @Test
    public void testSetMessage_Null() {
        String expectedMessage = null;
        errorResponse.setMessage(expectedMessage);
        assertEquals(expectedMessage, errorResponse.getMessage());
    }
}
