// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ErrorResponse_getErrorCodeb408c72345Test {

    @InjectMocks
    private ErrorResponse errorResponse;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
        errorResponse.setErrorCode(404);
    }

    @Test
    public void testGetErrorCode_Success() {
        int expected = 404;
        int actual = errorResponse.getErrorCode();
        assertEquals(expected, actual, "Expected and actual Error Codes do not match");
    }

    @Test
    public void testGetErrorCode_Failure() {
        int unexpected = 500;
        int actual = errorResponse.getErrorCode();
        assertNotEquals(unexpected, actual, "Error Code should not be 500");
    }
}
