// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.exception;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class ErrorResponse_setErrorCodeac0de600a7Test {

    private ErrorResponse errorResponse;

    @BeforeEach
    public void setUp() {
        errorResponse = new ErrorResponse();
    }

    @Test
    public void testSetErrorCode_Success() {
        int expectedErrorCode = 500;
        errorResponse.setErrorCode(expectedErrorCode);
        assertEquals(expectedErrorCode, errorResponse.getErrorCode(), "Error code should be set correctly.");
    }

    @Test
    public void testSetErrorCode_NegativeValue() {
        int expectedErrorCode = -1;
        errorResponse.setErrorCode(expectedErrorCode);
        assertEquals(expectedErrorCode, errorResponse.getErrorCode(), "Error code should be set correctly for negative values.");
    }
}
