// Test generated by RoostGPT for test dmtest using AI Type Open AI and AI Model gpt-4-0314

package com.example.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ErrorResponse_setMessage_41fefe61bb_Test {
    private ErrorResponse errorResponse;

    @BeforeEach
    public void setUp() {
        errorResponse = new ErrorResponse();
    }

    @Test
    public void testSetMessage_Success() {
        String expectedMessage = "This is a test message";
        errorResponse.setMessage(expectedMessage);
        assertEquals(expectedMessage, errorResponse.getMessage());
    }

    @Test
    public void testSetMessage_Null() {
        String expectedMessage = null;
        errorResponse.setMessage(expectedMessage);
        assertEquals(expectedMessage, errorResponse.getMessage());
    }
}
