// Test generated by RoostGPT for test dmtest using AI Type Open AI and AI Model gpt-4-0314

package com.example.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class RestExceptionHandler_exceptionToDoHandler_461f6e3924_Test {

    private RestExceptionHandler restExceptionHandler;

    @BeforeEach
    public void setUp() {
        restExceptionHandler = new RestExceptionHandler();
    }

    @Test
    public void testExceptionToDoHandler_validException() {
        Exception ex = new Exception("Test exception message");
        ResponseEntity<ErrorResponse> response = restExceptionHandler.exceptionToDoHandler(ex);

        assertEquals(HttpStatus.NOT_FOUND, response.getStatusCode());
        assertEquals(HttpStatus.NOT_FOUND.value(), response.getBody().getErrorCode());
        assertEquals("Test exception message", response.getBody().getMessage());
    }

    @Test
    public void testExceptionToDoHandler_emptyExceptionMessage() {
        Exception ex = new Exception("");
        ResponseEntity<ErrorResponse> response = restExceptionHandler.exceptionToDoHandler(ex);

        assertEquals(HttpStatus.NOT_FOUND, response.getStatusCode());
        assertEquals(HttpStatus.NOT_FOUND.value(), response.getBody().getErrorCode());
        assertEquals("", response.getBody().getMessage());
    }
}
