// Test generated by RoostGPT for test dmtest using AI Type Open AI and AI Model gpt-4-0314

package com.example.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class RestExceptionHandler_exceptionHandler_daaa553ebd_Test {

    private RestExceptionHandler restExceptionHandler;

    @BeforeEach
    public void setUp() {
        restExceptionHandler = new RestExceptionHandler();
    }

    @Test
    public void testExceptionHandler_validException() {
        Exception ex = new Exception("Test exception");
        ResponseEntity<ErrorResponse> response = restExceptionHandler.exceptionHandler(ex);

        assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
        assertEquals(HttpStatus.BAD_REQUEST.value(), response.getBody().getErrorCode());
        assertEquals("The request could not be understood by the server due to malformed syntax.", response.getBody().getMessage());
    }

    @Test
    public void testExceptionHandler_nullException() {
        ResponseEntity<ErrorResponse> response = restExceptionHandler.exceptionHandler(null);

        assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
        assertEquals(HttpStatus.BAD_REQUEST.value(), response.getBody().getErrorCode());
        assertEquals("The request could not be understood by the server due to malformed syntax.", response.getBody().getMessage());
    }
}
