// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class ToDoException_getErrorMessaged445c4b33dTest {

    @InjectMocks
    ToDoException toDoException;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        toDoException.setErrorMessage("Test Error Message");
    }

    @Test
    public void testGetErrorMessageSuccess() {
        String expectedErrorMessage = "Test Error Message";
        String actualErrorMessage = toDoException.getErrorMessage();
        assertEquals(expectedErrorMessage, actualErrorMessage, "Expected and actual error messages do not match");
    }

    @Test
    public void testGetErrorMessageFailure() {
        String expectedErrorMessage = "Different Error Message";
        String actualErrorMessage = toDoException.getErrorMessage();
        assertEquals(expectedErrorMessage, actualErrorMessage, "Expected and actual error messages do not match");
    }
}
