// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class ToDoException_ToDoException94d2102c18Test {

    private ToDoException toDoException;

    @BeforeEach
    public void setUp() {
        toDoException = new ToDoException();
    }

    @Test
    public void testToDoExceptionConstructor() {
        assertEquals(null, toDoException.getMessage());
    }

    @Test
    public void testToDoExceptionConstructorWithMessage() {
        String message = "Test exception message";
        toDoException = new ToDoException(message);
        assertEquals(message, toDoException.getMessage());
    }
}
