// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.service;

import com.example.model.ToDo;
import com.example.repository.ToDoRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.times;

public class ToDoServiceImpl_removeToDo410a8914bbTest {

    @Mock
    private ToDoRepository toDoRepository;

    @BeforeEach
    public void init() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testRemoveToDo_Success() {
        ToDo todo = new ToDo();
        todo.setId(1L);
        todo.setTitle("Test ToDo");

        toDoRepository.delete(todo);
        verify(toDoRepository, times(1)).delete(todo);
    }

    @Test
    public void testRemoveToDo_NullToDo() {
        ToDo todo = null;

        toDoRepository.delete(todo);
        verify(toDoRepository, times(1)).delete(todo);
    }
}
