// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.service;

import com.example.model.ToDo;
import com.example.repository.ToDoRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class ToDoServiceImpl_saveToDo3944cf9af7Test {

    @InjectMocks
    private ToDoServiceImpl toDoService;

    @Mock
    private ToDoRepository toDoRepository;

    @BeforeEach
    public void setup(){
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSaveToDo_success() {
        ToDo todo = new ToDo();
        todo.setId(1L);
        todo.setTask("Test Task");

        when(toDoRepository.save(any(ToDo.class))).thenReturn(todo);

        ToDo savedTodo = toDoService.saveToDo(todo);

        assertEquals(todo, savedTodo);
        verify(toDoRepository, times(1)).save(todo);
    }

    @Test
    public void testSaveToDo_failure() {
        ToDo todo = new ToDo();
        todo.setId(1L);
        todo.setTask("Test Task");

        when(toDoRepository.save(any(ToDo.class))).thenThrow(new RuntimeException("Exception occurred"));

        try {
            ToDo savedTodo = toDoService.saveToDo(todo);
        } catch (Exception e) {
            assertEquals("Exception occurred", e.getMessage());
        }

        verify(toDoRepository, times(1)).save(todo);
    }
}
