// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.service;

import com.example.model.ToDo;
import com.example.repository.ToDoRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.when;

public class ToDoServiceImpl_getToDoById593065db7eTest {

    @InjectMocks
    private ToDoServiceImpl toDoService;

    @Mock
    private ToDoRepository toDoRepository;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetToDoById_Success() {
        ToDo toDo = new ToDo();
        toDo.setId(1L);
        when(toDoRepository.findById(anyLong())).thenReturn(Optional.of(toDo));

        Optional<ToDo> result = toDoService.getToDoById(1L);

        assertTrue(result.isPresent());
        assertEquals(1L, result.get().getId());
    }

    @Test
    public void testGetToDoById_NotFound() {
        when(toDoRepository.findById(anyLong())).thenReturn(Optional.empty());

        Optional<ToDo> result = toDoService.getToDoById(1L);

        assertFalse(result.isPresent());
    }
}
