// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.service;

import com.example.model.ToDo;
import com.example.repository.ToDoRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.mockito.Mockito.*;

public class ToDoServiceImpl_removeToDo410a8914bbTest {

    @InjectMocks
    ToDoServiceImpl toDoService;

    @Mock
    ToDoRepository toDoRepository;

    @BeforeEach
    public void init() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testRemoveToDo_Success() {
        ToDo todo = new ToDo();
        todo.setId(1L);
        todo.setTitle("Test ToDo");
        todo.setDescription("This is a test ToDo");

        toDoService.removeToDo(todo);

        verify(toDoRepository, times(1)).delete(todo);
    }

    @Test
    public void testRemoveToDo_NullToDo() {
        ToDo todo = null;

        try {
            toDoService.removeToDo(todo);
        } catch (IllegalArgumentException e) {
            assert e.getMessage().equals("ToDo cannot be null");
        }

        verify(toDoRepository, times(0)).delete(any(ToDo.class));
    }
}
