// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.service;

import com.example.model.ToDo;
import com.example.repository.ToDoRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

public class ToDoServiceImpl_saveToDo3944cf9af7Test {

    @InjectMocks
    ToDoServiceImpl toDoService;

    @Mock
    ToDoRepository toDoRepository;

    @BeforeEach
    public void init() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testSaveToDo_Success() {
        ToDo todo = new ToDo();
        todo.setId(1L);
        todo.setTitle("Test ToDo");

        when(toDoRepository.save(any(ToDo.class))).thenReturn(todo);

        ToDo savedTodo = toDoService.saveToDo(todo);

        assertEquals(todo.getId(), savedTodo.getId());
        assertEquals(todo.getTitle(), savedTodo.getTitle());
    }

    @Test
    public void testSaveToDo_Failure() {
        ToDo todo = new ToDo();
        todo.setId(1L);
        todo.setTitle("Test ToDo");

        when(toDoRepository.save(any(ToDo.class))).thenThrow(new RuntimeException("Test Exception"));

        try {
            ToDo savedTodo = toDoService.saveToDo(todo);
        } catch (Exception e) {
            assertEquals("Test Exception", e.getMessage());
        }
    }
}
