// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.util;

import com.example.model.ToDo;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class PayloadValidator_validateCreatePayloadc70ae23adfTest {

    private ToDo toDo;

    @BeforeEach
    public void setUp() {
        toDo = new ToDo();
    }

    @Test
    public void testValidateCreatePayload_IdLessThanZero() {
        toDo.setId(-1);
        boolean result = PayloadValidator.validateCreatePayload(toDo);
        assertTrue(result, "Validation should return true when id is less than zero");
    }

    @Test
    public void testValidateCreatePayload_IdEqualToZero() {
        toDo.setId(0);
        boolean result = PayloadValidator.validateCreatePayload(toDo);
        assertTrue(result, "Validation should return true when id is equal to zero");
    }

    @Test
    public void testValidateCreatePayload_IdGreaterThanZero() {
        toDo.setId(1);
        boolean result = PayloadValidator.validateCreatePayload(toDo);
        assertFalse(result, "Validation should return false when id is greater than zero");
    }
}
