// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.model;

import static org.junit.Assert.assertNotNull;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class Response_Response22e96135c1Test {

    @Test
    public void testResponseCreation() {
        Response response = new Response();
        assertNotNull("Response object should not be null", response);
    }
}
