// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Response_getMessage6d271e6330Test {

    private Response response;

    @BeforeEach
    public void setup() {
        response = new Response();
    }

    @Test
    public void testGetMessageSuccess() {
        String expectedMessage = "Hello, World!";
        response.setMessage(expectedMessage);
        String actualMessage = response.getMessage();
        assertEquals(expectedMessage, actualMessage, "The expected message should match the actual message");
    }

    @Test
    public void testGetMessageNull() {
        String expectedMessage = null;
        response.setMessage(expectedMessage);
        String actualMessage = response.getMessage();
        assertEquals(expectedMessage, actualMessage, "The expected message should match the actual message");
    }
}
