// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Response_setStatusc599901da3Test {

    private Response response;

    @BeforeEach
    public void setUp() {
        response = new Response();
    }

    @Test
    public void testSetStatusPositive() {
        int status = 200;
        response.setStatus(status);
        assertEquals(status, response.getStatus(), "Status should be set to 200");
    }

    @Test
    public void testSetStatusNegative() {
        int status = -1;
        response.setStatus(status);
        assertEquals(status, response.getStatus(), "Status should be set to -1");
    }
}
