// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Response_Responsefb77d1f52aTest {

    private Response response;

    @BeforeEach
    public void setUp() {
        response = new Response(200, "Success");
    }

    @Test
    public void testResponseStatus() {
        assertEquals(200, response.getStatus(), "The status should be 200");
    }

    @Test
    public void testResponseMessage() {
        assertEquals("Success", response.getMessage(), "The message should be Success");
    }

    @Test
    public void testResponseWithDifferentStatus() {
        response = new Response(404, "Not Found");
        assertEquals(404, response.getStatus(), "The status should be 404");
        assertEquals("Not Found", response.getMessage(), "The message should be Not Found");
    }

    @Test
    public void testResponseWithEmptyMessage() {
        response = new Response(500, "");
        assertEquals(500, response.getStatus(), "The status should be 500");
        assertEquals("", response.getMessage(), "The message should be empty");
    }
}
