// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class ToDo_ToDo2d267193c4Test {
    private ToDo testToDo;

    @BeforeEach
    public void setUp() {
        testToDo = new ToDo();
    }

    @Test
    public void testToDoConstructor() {
        long id = 1;
        String text = "Test ToDo";
        boolean completed = false;

        testToDo = new ToDo(id, text, completed);

        assertEquals(id, testToDo.getId());
        assertEquals(text, testToDo.getText());
        assertEquals(completed, testToDo.isCompleted());
    }

    @Test
    public void testToDoConstructorWithEmptyText() {
        long id = 1;
        String text = "";
        boolean completed = false;

        testToDo = new ToDo(id, text, completed);

        assertEquals(id, testToDo.getId());
        assertEquals(text, testToDo.getText());
        assertEquals(completed, testToDo.isCompleted());
    }

    @Test
    public void testToDoConstructorWithNullText() {
        long id = 1;
        String text = null;
        boolean completed = false;

        testToDo = new ToDo(id, text, completed);

        assertEquals(id, testToDo.getId());
        assertNull(testToDo.getText());
        assertEquals(completed, testToDo.isCompleted());
    }

    @Test
    public void testToDoConstructorWithNegativeId() {
        long id = -1;
        String text = "Test ToDo";
        boolean completed = false;

        testToDo = new ToDo(id, text, completed);

        assertEquals(id, testToDo.getId());
        assertEquals(text, testToDo.getText());
        assertEquals(completed, testToDo.isCompleted());
    }
}
