// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ToDo_setCompleted152bcbf5fcTest {

    @InjectMocks
    private ToDo todo;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        todo = new ToDo();
    }

    @Test
    public void testSetCompletedTrue() {
        todo.setCompleted(true);
        assertEquals(true, todo.isCompleted(), "Expected and actual results do not match");
    }

    @Test
    public void testSetCompletedFalse() {
        todo.setCompleted(false);
        assertEquals(false, todo.isCompleted(), "Expected and actual results do not match");
    }
}
