// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class ToDo_getText2adcdf7ab0Test {

    @InjectMocks
    private ToDo toDo;

    @Mock
    private TextService textService;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
        toDo = new ToDo();
    }

    @Test
    public void testGetText_success() {
        // TODO: Change this to the expected text
        String expectedText = "Hello, World!";
        when(textService.getText()).thenReturn(expectedText);
        String actualText = toDo.getText();
        assertEquals(expectedText, actualText);
    }

    @Test
    public void testGetText_empty() {
        String expectedText = "";
        when(textService.getText()).thenReturn(expectedText);
        String actualText = toDo.getText();
        assertEquals(expectedText, actualText);
    }
}
