// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ToDo_setText69ff7df05eTest {

    private ToDo todo;

    @BeforeEach
    public void setup() {
        todo = new ToDo();
    }

    @Test
    public void testSetText_Success() {
        String expectedText = "This is a test text";
        todo.setText(expectedText);
        assertEquals(expectedText, todo.getText());
    }

    @Test
    public void testSetText_Empty() {
        String expectedText = "";
        todo.setText(expectedText);
        assertEquals(expectedText, todo.getText());
    }

    @Test
    public void testSetText_Null() {
        String expectedText = null;
        todo.setText(expectedText);
        assertEquals(expectedText, todo.getText());
    }
}
