// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class ToDo_isCompleted86882206cfTest {

    private ToDo toDo;

    @BeforeEach
    public void setUp() {
        toDo = new ToDo();
    }

    @Test
    public void testIsCompleted_whenTaskIsCompleted() {
        toDo.setCompleted(true);
        assertTrue(toDo.isCompleted());
    }

    @Test
    public void testIsCompleted_whenTaskIsNotCompleted() {
        toDo.setCompleted(false);
        assertFalse(toDo.isCompleted());
    }
}
