// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ToDo_ToDob94e8fdfddTest {

    private ToDo toDo;

    @BeforeEach
    public void setup() {
        toDo = new ToDo("Test ToDo", false);
    }

    @Test
    public void testToDoConstructor() {
        assertEquals("Test ToDo", toDo.getText());
        assertEquals(false, toDo.isCompleted());
    }

    @Test
    public void testToDoConstructorWithEmptyText() {
        ToDo toDoWithEmptyText = new ToDo("", false);
        assertEquals("", toDoWithEmptyText.getText());
        assertEquals(false, toDoWithEmptyText.isCompleted());
    }
}
