// Test generated by RoostGPT for test dmtest using AI Type Open AI and AI Model gpt-4-0314

package com.example.model;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

@Entity
public class ToDo_ToDo_6a8489450f_Test {

    private ToDo toDo;

    @BeforeEach
    public void setUp() {
        toDo = new ToDo(1L, "Test task", false);
    }

    @Test
    public void testConstructorId() {
        long expectedId = 1L;
        assertEquals(expectedId, toDo.getId());
    }

    @Test
    public void testConstructorText() {
        String expectedText = "Test task";
        assertEquals(expectedText, toDo.getText());
    }

    @Test
    public void testConstructorCompleted() {
        boolean expectedCompleted = false;
        assertEquals(expectedCompleted, toDo.isCompleted());
    }
}
