// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class ToDo_getIdac2bd64fc7Test {

    private ToDo toDo;

    @BeforeEach
    public void setup() {
        toDo = Mockito.mock(ToDo.class);
    }

    @Test
    public void testGetIdSuccess() {
        // TODO: Replace the value of 123L with the actual id of the ToDo item.
        when(toDo.getId()).thenReturn(123L);
        long expectedId = 123L;
        long actualId = toDo.getId();
        assertEquals(expectedId, actualId, "The expected id should match the actual id.");
    }

    @Test
    public void testGetIdFailure() {
        // TODO: Replace the value of 456L with the actual id of the ToDo item.
        when(toDo.getId()).thenReturn(456L);
        long unexpectedId = 123L;
        long actualId = toDo.getId();
        assertNotEquals(unexpectedId, actualId, "The unexpected id should not match the actual id.");
    }
}
