// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ToDo_ToDo2d267193c4Test {

    private ToDo testToDo;

    @BeforeEach
    public void setUp() {
        testToDo = new ToDo(1, "Test task", false);
    }

    @Test
    public void testToDoConstructor_Success() {
        assertEquals(1, testToDo.getId());
        assertEquals("Test task", testToDo.getText());
        assertFalse(testToDo.isCompleted());
    }

    @Test
    public void testToDoConstructor_Failure() {
        assertNotEquals(2, testToDo.getId());
        assertNotEquals("Different task", testToDo.getText());
        assertTrue(!testToDo.isCompleted());
    }
}
