// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ToDo_setText69ff7df05eTest {
    private ToDo todo;

    @BeforeEach
    public void setUp() {
        todo = new ToDo();
    }

    @Test
    public void testSetText() {
        String text = "Test ToDo item";
        todo.setText(text);
        assertEquals(text, todo.getText(), "Expected text to be set correctly");
    }

    @Test
    public void testSetTextWithEmptyString() {
        String text = "";
        todo.setText(text);
        assertEquals(text, todo.getText(), "Expected text to be set correctly even with empty string");
    }

    @Test
    public void testSetTextWithNull() {
        String text = null;
        // TODO: Change the value of text if required
        todo.setText(text);
        assertEquals(text, todo.getText(), "Expected text to be set correctly even with null value");
    }
}
