// Test generated by RoostGPT for test dm-example-4 using AI Model gpt

package com.example.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ToDo_getText2adcdf7ab0Test {

    private ToDo toDo;

    @BeforeEach
    public void setup() {
        toDo = new ToDo();
    }

    @Test
    public void testGetText_whenTextIsSet() {
        String expectedText = "This is a test text";
        toDo.setText(expectedText);
        String actualText = toDo.getText();
        assertEquals(expectedText, actualText, "Expected text does not match the actual text");
    }

    @Test
    public void testGetText_whenTextIsNotSet() {
        String expectedText = null;
        String actualText = toDo.getText();
        assertEquals(expectedText, actualText, "Expected text does not match the actual text");
    }
}
